import {
  Tenant,
  User,
  Customer,
  Lead,
  TranslationService,
  Language,
  InboundRequest,
  Quote,
  WorkOrder,
  DocumentItem,
  OrderTask,
  Translator,
  Reviewer,
  AccountReceivable,
  AccountPayable,
  Expense,
  NotificationItem,
  AuditLog,
} from '@/types';

export const INITIAL_TENANT: Tenant = {
  id: 'traduztudo-matriz',
  name: 'TraduzTudo — Traduções Juramentadas e Certificadas',
  slug: 'traduztudo',
  document: '34.123.456/0001-89',
  email: 'contato@traduztudo.com.br',
  phone: '(11) 4003-8990',
  whatsapp: '(11) 98765-4321',
  website: 'https://traduztudo.vercel.app',
  address: {
    street: 'Av. Paulista',
    number: '1842',
    complement: 'Torre Norte - 14º andar',
    neighborhood: 'Bela Vista',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01310-200',
    country: 'Brasil',
  },
  plan: 'PRO',
  active: true,
  createdAt: '2026-01-10T09:00:00.000Z',
  updatedAt: '2026-09-30T10:00:00.000Z',
};

export const INITIAL_USERS: User[] = [
  {
    id: 'user-carlos',
    tenantId: 'traduztudo-matriz',
    name: 'Carlos Silva',
    email: 'carlos@traduztudo.com.br',
    role: 'OWNER',
    phone: '(11) 98111-2233',
    active: true,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'user-mariana',
    tenantId: 'traduztudo-matriz',
    name: 'Mariana Costa',
    email: 'mariana@traduztudo.com.br',
    role: 'MANAGER',
    phone: '(11) 98222-3344',
    active: true,
    createdAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'user-juliana',
    tenantId: 'traduztudo-matriz',
    name: 'Juliana Mendes',
    email: 'juliana@traduztudo.com.br',
    role: 'ATTENDANT',
    phone: '(11) 98333-4455',
    active: true,
    createdAt: '2026-02-01T08:30:00.000Z',
  },
  {
    id: 'user-rodrigo',
    tenantId: 'traduztudo-matriz',
    name: 'Rodrigo Rocha',
    email: 'rodrigo@traduztudo.com.br',
    role: 'FINANCE',
    phone: '(11) 98444-5566',
    active: true,
    createdAt: '2026-02-10T11:00:00.000Z',
  },
];

export const INITIAL_SERVICES: TranslationService[] = [
  {
    id: 'srv-juramentada',
    tenantId: 'traduztudo-matriz',
    name: 'Tradução Juramentada',
    code: 'juramentada',
    description: 'Tradução oficial com fé pública realizada por tradutor público juramentado juramentado na junta comercial.',
    unit: 'lauda',
    defaultPrice: 95.0,
    defaultTurnaroundDays: 3,
    active: true,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'srv-certificada',
    tenantId: 'traduztudo-matriz',
    name: 'Tradução Certificada',
    code: 'certificada',
    description: 'Tradução acompanhada de declaração de exatidão e carimbo profissional para uso internacional.',
    unit: 'lauda',
    defaultPrice: 80.0,
    defaultTurnaroundDays: 2,
    active: true,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'srv-tecnica',
    tenantId: 'traduztudo-matriz',
    name: 'Tradução Técnica Especializada',
    code: 'tecnica',
    description: 'Tradução para áreas jurídica, engenharia, médica, farmacêutica e tecnologia por linguistas especialistas.',
    unit: 'palavra',
    defaultPrice: 0.38,
    defaultTurnaroundDays: 4,
    active: true,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'srv-simples',
    tenantId: 'traduztudo-matriz',
    name: 'Tradução Simples / Livre',
    code: 'simples',
    description: 'Tradução sem valor jurídico para fins de leitura, correspondências e artigos informativos.',
    unit: 'palavra',
    defaultPrice: 0.25,
    defaultTurnaroundDays: 2,
    active: true,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'srv-revisao',
    tenantId: 'traduztudo-matriz',
    name: 'Revisão Linguística e Formatação',
    code: 'revisao',
    description: 'Conferência minuciosa de fidelidade, terminologia, fluidez e adequação gramatical.',
    unit: 'palavra',
    defaultPrice: 0.15,
    defaultTurnaroundDays: 2,
    active: true,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'srv-apostilamento',
    tenantId: 'traduztudo-matriz',
    name: 'Apostilamento de Haia',
    code: 'apostilamento',
    description: 'Autenticação cartorária de documentos públicos de acordo com a Convenção de Haia.',
    unit: 'documento',
    defaultPrice: 190.0,
    defaultTurnaroundDays: 5,
    active: true,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
];

export const INITIAL_LANGUAGES: Language[] = [
  { id: 'lang-pt', tenantId: 'traduztudo-matriz', code: 'pt', name: 'Português', nativeName: 'Português', active: true },
  { id: 'lang-en', tenantId: 'traduztudo-matriz', code: 'en', name: 'Inglês', nativeName: 'English', active: true },
  { id: 'lang-es', tenantId: 'traduztudo-matriz', code: 'es', name: 'Espanhol', nativeName: 'Español', active: true },
  { id: 'lang-fr', tenantId: 'traduztudo-matriz', code: 'fr', name: 'Francês', nativeName: 'Français', active: true },
  { id: 'lang-it', tenantId: 'traduztudo-matriz', code: 'it', name: 'Italiano', nativeName: 'Italiano', active: true },
  { id: 'lang-de', tenantId: 'traduztudo-matriz', code: 'de', name: 'Alemão', nativeName: 'Deutsch', active: true },
  { id: 'lang-zh', tenantId: 'traduztudo-matriz', code: 'zh', name: 'Mandarim', nativeName: '中文', active: true },
  { id: 'lang-ja', tenantId: 'traduztudo-matriz', code: 'ja', name: 'Japonês', nativeName: '日本語', active: true },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cli-001',
    tenantId: 'traduztudo-matriz',
    type: 'PF',
    name: 'Dr. Roberto Alencar',
    cpf: '23456789012',
    email: 'roberto.alencar@medicina.ufrj.br',
    phone: '21988887766',
    whatsapp: '21988887766',
    street: 'Rua Visconde de Pirajá',
    number: '414',
    complement: 'Apt 802',
    neighborhood: 'Ipanema',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '22410-002',
    country: 'Brasil',
    notes: 'Médico cirurgião validando diploma nos EUA junto à ECFMG.',
    totalSpent: 4250.0,
    ordersCount: 3,
    activeOrdersCount: 1,
    pendingBalance: 0,
    lastContactAt: '2026-09-28T14:30:00.000Z',
    createdAt: '2026-02-12T11:00:00.000Z',
    updatedAt: '2026-09-28T14:30:00.000Z',
  },
  {
    id: 'cli-002',
    tenantId: 'traduztudo-matriz',
    type: 'PJ',
    name: 'TechNova Brasil Tecnologia Ltda',
    companyName: 'TechNova Brasil Tecnologia Ltda',
    tradeName: 'TechNova',
    cnpj: '12345678000195',
    contactPerson: 'Fernanda Lins (Diretora Jurídica)',
    email: 'juridico@technovabrasil.com.br',
    phone: '1133334444',
    whatsapp: '11999998888',
    street: 'Av. Brigadeiro Faria Lima',
    number: '3477',
    complement: '12º andar',
    neighborhood: 'Itaim Bibi',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04538-133',
    country: 'Brasil',
    notes: 'Contratos corporativos de M&A e acordos de acionistas com fundo americano.',
    totalSpent: 12800.0,
    ordersCount: 5,
    activeOrdersCount: 2,
    pendingBalance: 3200.0,
    lastContactAt: '2026-09-29T16:00:00.000Z',
    createdAt: '2026-03-05T09:20:00.000Z',
    updatedAt: '2026-09-29T16:00:00.000Z',
  },
  {
    id: 'cli-003',
    tenantId: 'traduztudo-matriz',
    type: 'PF',
    name: 'Beatriz Montenegro',
    cpf: '34567890123',
    email: 'beatriz.monte@gmail.com',
    phone: '11977776655',
    whatsapp: '11977776655',
    street: 'Rua Oscar Freire',
    number: '920',
    complement: 'Apt 31',
    neighborhood: 'Cerqueira César',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01426-000',
    country: 'Brasil',
    notes: 'Processo de cidadania italiana (certidões de nascimento, casamento e óbito com apostilamento).',
    totalSpent: 3100.0,
    ordersCount: 2,
    activeOrdersCount: 1,
    pendingBalance: 1550.0,
    lastContactAt: '2026-09-29T11:15:00.000Z',
    createdAt: '2026-04-18T10:00:00.000Z',
    updatedAt: '2026-09-29T11:15:00.000Z',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-001',
    tenantId: 'traduztudo-matriz',
    name: 'Guilherme Siqueira',
    type: 'PF',
    email: 'guilherme.siq@hotmail.com',
    phone: '11966554433',
    whatsapp: '11966554433',
    origin: 'Site TraduzTudo',
    interestedServiceName: 'Tradução Juramentada',
    sourceLanguage: 'Português',
    targetLanguage: 'Inglês',
    estimatedVolume: '4 documentos (Histórico escolar e diploma)',
    notes: 'Quer orçamento urgente para visto de estudante no Canadá.',
    assignedUserName: 'Juliana Mendes',
    status: 'orcamento_enviado',
    createdAt: '2026-09-29T08:30:00.000Z',
    updatedAt: '2026-09-29T10:00:00.000Z',
  },
  {
    id: 'lead-002',
    tenantId: 'traduztudo-matriz',
    name: 'Metalúrgica Vulcanus S.A.',
    type: 'PJ',
    email: 'compras@vulcanus.ind.br',
    phone: '1938009988',
    whatsapp: '19981223344',
    origin: 'Indicação Comercial',
    interestedServiceName: 'Tradução Técnica Especializada',
    sourceLanguage: 'Alemão',
    targetLanguage: 'Português',
    estimatedVolume: '120.000 palavras (Manuais de maquinário industrial)',
    notes: 'Importação de maquinário pesado da Alemanha. Avaliando proposta de 3 agências.',
    assignedUserName: 'Mariana Costa',
    status: 'negociacao',
    createdAt: '2026-09-25T14:00:00.000Z',
    updatedAt: '2026-09-29T15:20:00.000Z',
  },
  {
    id: 'lead-003',
    tenantId: 'traduztudo-matriz',
    name: 'Camila Drummond',
    type: 'PF',
    email: 'camila.drummond@adv.oab.org.br',
    phone: '31998761234',
    whatsapp: '31998761234',
    origin: 'Site TraduzTudo',
    interestedServiceName: 'Apostilamento de Haia',
    sourceLanguage: 'Português',
    targetLanguage: 'Espanhol',
    estimatedVolume: '6 certidões de inventário',
    notes: 'Inventário transnacional na Espanha.',
    assignedUserName: 'Juliana Mendes',
    status: 'novo',
    createdAt: '2026-09-30T01:15:00.000Z',
    updatedAt: '2026-09-30T01:15:00.000Z',
  },
  {
    id: 'lead-004',
    tenantId: 'traduztudo-matriz',
    name: 'Dr. Roberto Alencar',
    type: 'PF',
    email: 'roberto.alencar@medicina.ufrj.br',
    phone: '21988887766',
    origin: 'Site TraduzTudo',
    interestedServiceName: 'Tradução Juramentada',
    sourceLanguage: 'Português',
    targetLanguage: 'Inglês',
    status: 'convertido',
    customerId: 'cli-001',
    createdAt: '2026-02-10T10:00:00.000Z',
    updatedAt: '2026-02-12T11:00:00.000Z',
  },
];

export const INITIAL_TRANSLATORS: Translator[] = [
  {
    id: 'trans-lucas',
    tenantId: 'traduztudo-matriz',
    name: 'Lucas Andrade',
    email: 'lucas.tradutor@gmail.com',
    phone: '11984561234',
    whatsapp: '11984561234',
    languages: ['Inglês -> Português', 'Português -> Inglês'],
    specialties: ['Juramentada JUCESP', 'Jurídica', 'Acadêmica'],
    contractType: 'freelancer',
    ratePerWord: 0.18,
    ratePerLauda: 48.0,
    bankInfo: 'Banco Itaú - Ag 0123 CC 98765-4',
    pixKey: 'lucas.tradutor@gmail.com',
    active: true,
    assignedOrdersCount: 2,
    completedOrdersCount: 47,
    pendingPaymentAmount: 1840.0,
    notes: 'Tradutor público juramentado credenciado com excelente pontualidade.',
    createdAt: '2026-01-20T10:00:00.000Z',
  },
  {
    id: 'trans-elena',
    tenantId: 'traduztudo-matriz',
    name: 'Elena Rossi',
    email: 'elena.rossi@traduzioni.it',
    phone: '11976543210',
    whatsapp: '11976543210',
    languages: ['Italiano -> Português', 'Português -> Italiano', 'Espanhol -> Português'],
    specialties: ['Cidadania Italiana', 'Contratos', 'Históricos'],
    contractType: 'pj',
    ratePerWord: 0.20,
    ratePerLauda: 52.0,
    pixKey: '33.444.555/0001-22',
    active: true,
    assignedOrdersCount: 1,
    completedOrdersCount: 34,
    pendingPaymentAmount: 950.0,
    notes: 'Especialista em processos consulares para Itália e Espanha.',
    createdAt: '2026-02-05T14:00:00.000Z',
  },
  {
    id: 'trans-klaus',
    tenantId: 'traduztudo-matriz',
    name: 'Klaus Schmidt',
    email: 'klaus.schmidt@berlin-tech.de',
    phone: '11998877665',
    languages: ['Alemão -> Português', 'Português -> Alemão'],
    specialties: ['Técnica', 'Engenharia', 'Patentes'],
    contractType: 'pj',
    ratePerWord: 0.24,
    ratePerLauda: 60.0,
    pixKey: 'klaus.pix@banco.com',
    active: true,
    assignedOrdersCount: 0,
    completedOrdersCount: 18,
    pendingPaymentAmount: 0,
    createdAt: '2026-03-01T09:00:00.000Z',
  },
];

export const INITIAL_REVIEWERS: Reviewer[] = [
  {
    id: 'rev-fernando',
    tenantId: 'traduztudo-matriz',
    name: 'Fernando Alvarez',
    email: 'fernando.revisor@gmail.com',
    phone: '11991234567',
    languages: ['Inglês', 'Espanhol', 'Italiano'],
    specialties: ['Revisão Terminológica', 'Conformidade Notarial'],
    contractType: 'pj',
    active: true,
    assignedOrdersCount: 2,
    completedOrdersCount: 82,
    pendingPaymentAmount: 420.0,
    notes: 'Revisor sênior, ex-advogado internacional com atenção extrema a detalhes.',
    createdAt: '2026-01-25T11:00:00.000Z',
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 'quote-001',
    tenantId: 'traduztudo-matriz',
    code: 'ORC-000001',
    customerId: 'cli-001',
    customerName: 'Dr. Roberto Alencar',
    customerEmail: 'roberto.alencar@medicina.ufrj.br',
    customerPhone: '21988887766',
    customerDocument: '234.567.890-12',
    assignedUserId: 'user-juliana',
    assignedUserName: 'Juliana Mendes',
    issueDate: '2026-09-20T10:00:00.000Z',
    expirationDate: '2026-10-05T23:59:59.000Z',
    estimatedDeliveryDays: 3,
    items: [
      {
        id: 'item-1',
        serviceId: 'srv-juramentada',
        serviceName: 'Tradução Juramentada',
        description: 'Tradução Juramentada de Diploma de Medicina e Histórico Escolar Completo',
        sourceLanguage: 'Português',
        targetLanguage: 'Inglês',
        quantity: 12,
        unit: 'lauda',
        unitPrice: 95.0,
        discount: 50.0,
        total: 1090.0,
      },
      {
        id: 'item-2',
        serviceId: 'srv-apostilamento',
        serviceName: 'Apostilamento de Haia',
        description: 'Apostilamento em Cartório Notarial dos documentos originais e traduções',
        quantity: 4,
        unit: 'documento',
        unitPrice: 190.0,
        discount: 0,
        total: 760.0,
      },
    ],
    subtotal: 1900.0,
    discount: 50.0,
    additionalCost: 0,
    total: 1850.0,
    conditions: 'Pagamento em 50% de entrada via PIX e 50% na entrega digital dos arquivos juramentados.',
    notes: 'Prazo contado a partir do envio de todos os documentos originais legíveis.',
    status: 'aprovado',
    approvalToken: 'token_abc123_roberto_alencar',
    approvedAt: '2026-09-21T14:20:00.000Z',
    approvedIp: '189.40.72.115',
    workOrderId: 'order-001',
    createdAt: '2026-09-20T10:00:00.000Z',
    updatedAt: '2026-09-21T14:20:00.000Z',
  },
  {
    id: 'quote-002',
    tenantId: 'traduztudo-matriz',
    code: 'ORC-000002',
    customerId: 'cli-002',
    customerName: 'TechNova Brasil Tecnologia Ltda',
    customerEmail: 'juridico@technovabrasil.com.br',
    customerPhone: '1133334444',
    customerDocument: '12.345.678/0001-95',
    assignedUserId: 'user-mariana',
    assignedUserName: 'Mariana Costa',
    issueDate: '2026-09-27T15:00:00.000Z',
    expirationDate: '2026-10-07T23:59:59.000Z',
    estimatedDeliveryDays: 4,
    items: [
      {
        id: 'item-1',
        serviceId: 'srv-tecnica',
        serviceName: 'Tradução Técnica Especializada',
        description: 'Contrato de Aquisição e Licenciamento de Software e Acordo de Confidencialidade',
        sourceLanguage: 'Inglês',
        targetLanguage: 'Português',
        quantity: 8500,
        unit: 'palavra',
        unitPrice: 0.38,
        discount: 30.0,
        total: 3200.0,
      },
    ],
    subtotal: 3230.0,
    discount: 30.0,
    additionalCost: 0,
    total: 3200.0,
    conditions: 'Faturamento para 15 dias após entrega, boleto bancário corporativo.',
    notes: 'Prioridade alta para fechamento de rodada societária.',
    status: 'enviado',
    approvalToken: 'token_technova_m_and_a_2026',
    createdAt: '2026-09-27T15:00:00.000Z',
    updatedAt: '2026-09-27T15:30:00.000Z',
  },
  {
    id: 'quote-003',
    tenantId: 'traduztudo-matriz',
    code: 'ORC-000003',
    customerId: 'cli-003',
    customerName: 'Beatriz Montenegro',
    customerEmail: 'beatriz.monte@gmail.com',
    customerPhone: '11977776655',
    customerDocument: '345.678.901-23',
    assignedUserId: 'user-juliana',
    assignedUserName: 'Juliana Mendes',
    issueDate: '2026-09-29T10:00:00.000Z',
    expirationDate: '2026-10-14T23:59:59.000Z',
    estimatedDeliveryDays: 5,
    items: [
      {
        id: 'item-1',
        serviceId: 'srv-juramentada',
        serviceName: 'Tradução Juramentada',
        description: 'Certidões em Inteiro Teor (Nascimento, Casamento e Óbito do Dante Causa)',
        sourceLanguage: 'Português',
        targetLanguage: 'Italiano',
        quantity: 15,
        unit: 'lauda',
        unitPrice: 95.0,
        discount: 0,
        total: 1425.0,
      },
      {
        id: 'item-2',
        serviceId: 'srv-apostilamento',
        serviceName: 'Apostilamento de Haia',
        description: 'Apostilamento das 3 certidões e das respectivas traduções',
        quantity: 6,
        unit: 'documento',
        unitPrice: 190.0,
        discount: 0,
        total: 1140.0,
      },
    ],
    subtotal: 2565.0,
    discount: 65.0,
    additionalCost: 0,
    total: 2500.0,
    conditions: 'PIX à vista com 5% de desconto ou 3x sem juros.',
    status: 'rascunho',
    approvalToken: 'token_beatriz_cidadania_it',
    createdAt: '2026-09-29T10:00:00.000Z',
    updatedAt: '2026-09-29T10:00:00.000Z',
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'order-001',
    tenantId: 'traduztudo-matriz',
    code: 'OS-000001',
    quoteId: 'quote-001',
    quoteCode: 'ORC-000001',
    customerId: 'cli-001',
    customerName: 'Dr. Roberto Alencar',
    customerEmail: 'roberto.alencar@medicina.ufrj.br',
    customerPhone: '21988887766',
    serviceName: 'Tradução Juramentada + Apostilamento',
    sourceLanguage: 'Português',
    targetLanguage: 'Inglês',
    priority: 'alta',
    deadline: '2026-10-03T18:00:00.000Z',
    assignedUserId: 'user-mariana',
    assignedUserName: 'Mariana Costa',
    translatorId: 'trans-lucas',
    translatorName: 'Lucas Andrade',
    reviewerId: 'rev-fernando',
    reviewerName: 'Fernando Alvarez',
    amount: 1850.0,
    paidAmount: 925.0,
    paymentStatus: 'parcial',
    status: 'em_traducao',
    notes: 'Dr. Roberto precisa do documento certificado digitalmente com assinatura ICP-Brasil.',
    createdAt: '2026-09-21T14:30:00.000Z',
    updatedAt: '2026-09-28T16:00:00.000Z',
  },
  {
    id: 'order-002',
    tenantId: 'traduztudo-matriz',
    code: 'OS-000002',
    customerId: 'cli-003',
    customerName: 'Beatriz Montenegro',
    customerEmail: 'beatriz.monte@gmail.com',
    customerPhone: '11977776655',
    serviceName: 'Tradução Juramentada (Cidadania)',
    sourceLanguage: 'Português',
    targetLanguage: 'Italiano',
    priority: 'normal',
    deadline: '2026-10-06T18:00:00.000Z',
    assignedUserId: 'user-juliana',
    assignedUserName: 'Juliana Mendes',
    translatorId: 'trans-elena',
    translatorName: 'Elena Rossi',
    reviewerId: 'rev-fernando',
    reviewerName: 'Fernando Alvarez',
    amount: 1550.0,
    paidAmount: 0,
    paymentStatus: 'pendente',
    status: 'documentos_recebidos',
    notes: 'Aguardando confirmação do cartório para iniciar apostilamento.',
    createdAt: '2026-09-25T11:00:00.000Z',
    updatedAt: '2026-09-26T14:00:00.000Z',
  },
  {
    id: 'order-003',
    tenantId: 'traduztudo-matriz',
    code: 'OS-000003',
    customerId: 'cli-002',
    customerName: 'TechNova Brasil Tecnologia Ltda',
    customerEmail: 'juridico@technovabrasil.com.br',
    customerPhone: '1133334444',
    serviceName: 'Tradução Certificada Contratos',
    sourceLanguage: 'Inglês',
    targetLanguage: 'Português',
    priority: 'urgente',
    deadline: '2026-09-30T19:00:00.000Z',
    assignedUserId: 'user-mariana',
    assignedUserName: 'Mariana Costa',
    translatorId: 'trans-lucas',
    translatorName: 'Lucas Andrade',
    reviewerId: 'rev-fernando',
    reviewerName: 'Fernando Alvarez',
    amount: 3200.0,
    paidAmount: 3200.0,
    paymentStatus: 'pago',
    status: 'em_revisao',
    notes: 'Revisão terminológica dos termos de propriedade intelectual em andamento.',
    createdAt: '2026-09-26T09:00:00.000Z',
    updatedAt: '2026-09-30T02:00:00.000Z',
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-001',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-001',
    customerId: 'cli-001',
    name: 'Diploma_Medicina_Roberto_Alencar.pdf',
    category: 'original',
    fileUrl: '/uploads/diploma_roberto_alencar.pdf',
    fileSize: 2450000,
    fileType: 'application/pdf',
    version: 1,
    uploaderUserId: 'user-juliana',
    uploaderName: 'Juliana Mendes',
    downloadCount: 4,
    createdAt: '2026-09-21T14:35:00.000Z',
  },
  {
    id: 'doc-002',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-001',
    customerId: 'cli-001',
    name: 'Historico_Escolar_UFRJ.pdf',
    category: 'original',
    fileUrl: '/uploads/historico_ufrj.pdf',
    fileSize: 4120000,
    fileType: 'application/pdf',
    version: 1,
    uploaderUserId: 'user-juliana',
    uploaderName: 'Juliana Mendes',
    downloadCount: 3,
    createdAt: '2026-09-21T14:36:00.000Z',
  },
  {
    id: 'doc-003',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-001',
    customerId: 'cli-001',
    name: 'Rascunho_Traducao_EN_v1.docx',
    category: 'trabalho',
    fileUrl: '/uploads/rascunho_traducao_en.docx',
    fileSize: 189000,
    fileType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    version: 1,
    uploaderUserId: 'trans-lucas',
    uploaderName: 'Lucas Andrade',
    downloadCount: 2,
    createdAt: '2026-09-27T18:00:00.000Z',
  },
  {
    id: 'doc-004',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-001',
    customerId: 'cli-001',
    name: 'Comprovante_PIX_Entrada_50pct.pdf',
    category: 'comprovante',
    fileUrl: '/uploads/comprovante_pix_925.pdf',
    fileSize: 312000,
    fileType: 'application/pdf',
    version: 1,
    uploaderUserId: 'user-juliana',
    uploaderName: 'Juliana Mendes',
    downloadCount: 1,
    createdAt: '2026-09-21T15:00:00.000Z',
  },
];

export const INITIAL_TASKS: OrderTask[] = [
  {
    id: 'tsk-001',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-001',
    title: 'Digitalização e conferência dos carimbos do diploma',
    description: 'Checar carimbos do MEC e assinaturas da reitoria para a tradução juramentada.',
    assignedToName: 'Mariana Costa',
    dueDate: '2026-09-22T18:00:00.000Z',
    priority: 'alta',
    status: 'concluida',
    createdAt: '2026-09-21T14:40:00.000Z',
    completedAt: '2026-09-22T16:00:00.000Z',
  },
  {
    id: 'tsk-002',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-001',
    title: 'Traduzir Diploma e Histórico (12 laudas)',
    description: 'Tradução para inglês com certificação JUCESP.',
    assignedToName: 'Lucas Andrade',
    dueDate: '2026-10-01T18:00:00.000Z',
    priority: 'alta',
    status: 'em_andamento',
    createdAt: '2026-09-21T14:45:00.000Z',
  },
  {
    id: 'tsk-003',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-001',
    title: 'Revisão terminológica e confrontação de notas médicas',
    description: 'Equivalência de créditos para o padrão norte-americano GPA.',
    assignedToName: 'Fernando Alvarez',
    dueDate: '2026-10-02T18:00:00.000Z',
    priority: 'normal',
    status: 'a_fazer',
    createdAt: '2026-09-21T14:45:00.000Z',
  },
];

export const INITIAL_RECEIVABLES: AccountReceivable[] = [
  {
    id: 'rec-001',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-001',
    workOrderCode: 'OS-000001',
    quoteId: 'quote-001',
    customerId: 'cli-001',
    customerName: 'Dr. Roberto Alencar',
    description: 'Entrada 50% - OS-000001 (Tradução Juramentada e Apostilamento)',
    amount: 925.0,
    paidAmount: 925.0,
    dueDate: '2026-09-21T23:59:59.000Z',
    paymentMethod: 'pix',
    status: 'pago',
    paidAt: '2026-09-21T15:10:00.000Z',
    notes: 'PIX confirmado e liquidado.',
    createdAt: '2026-09-21T14:30:00.000Z',
  },
  {
    id: 'rec-002',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-001',
    workOrderCode: 'OS-000001',
    quoteId: 'quote-001',
    customerId: 'cli-001',
    customerName: 'Dr. Roberto Alencar',
    description: 'Saldo 50% - OS-000001 (Entrega final)',
    amount: 925.0,
    paidAmount: 0,
    dueDate: '2026-10-03T23:59:59.000Z',
    paymentMethod: 'pix',
    status: 'pendente',
    createdAt: '2026-09-21T14:30:00.000Z',
  },
  {
    id: 'rec-003',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-003',
    workOrderCode: 'OS-000003',
    customerId: 'cli-002',
    customerName: 'TechNova Brasil Tecnologia Ltda',
    description: 'Faturamento Integral Contrato TechNova - OS-000003',
    amount: 3200.0,
    paidAmount: 3200.0,
    dueDate: '2026-09-29T23:59:59.000Z',
    paymentMethod: 'boleto',
    status: 'pago',
    paidAt: '2026-09-28T10:45:00.000Z',
    createdAt: '2026-09-26T09:00:00.000Z',
  },
  {
    id: 'rec-004',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-002',
    workOrderCode: 'OS-000002',
    customerId: 'cli-003',
    customerName: 'Beatriz Montenegro',
    description: 'Honorários Tradução Certidões - OS-000002',
    amount: 1550.0,
    paidAmount: 0,
    dueDate: '2026-10-06T23:59:59.000Z',
    paymentMethod: 'cartao_credito',
    status: 'pendente',
    createdAt: '2026-09-25T11:00:00.000Z',
  },
];

export const INITIAL_PAYABLES: AccountPayable[] = [
  {
    id: 'pay-001',
    tenantId: 'traduztudo-matriz',
    workOrderId: 'order-001',
    workOrderCode: 'OS-000001',
    recipientType: 'tradutor',
    recipientId: 'trans-lucas',
    recipientName: 'Lucas Andrade',
    description: 'Honorários Tradução Juramentada (12 laudas)',
    category: 'tradutores',
    amount: 576.0,
    dueDate: '2026-10-05T23:59:59.000Z',
    status: 'pendente',
    notes: 'Pagamento programado para o 5º dia útil após entrega.',
    createdAt: '2026-09-21T14:45:00.000Z',
  },
  {
    id: 'pay-002',
    tenantId: 'traduztudo-matriz',
    recipientType: 'fornecedor',
    recipientName: 'Cartório do 14º Tabelionato Notarial',
    description: 'Taxas cartorárias de Apostilamento de Haia (4 selos)',
    category: 'outros',
    amount: 520.0,
    dueDate: '2026-10-02T23:59:59.000Z',
    status: 'pendente',
    createdAt: '2026-09-21T14:50:00.000Z',
  },
  {
    id: 'pay-003',
    tenantId: 'traduztudo-matriz',
    recipientType: 'fornecedor',
    recipientName: 'Amazon Web Services / Cloud Server',
    description: 'Hospedagem infraestrutura SaaS e storage seguro',
    category: 'software',
    amount: 280.0,
    dueDate: '2026-10-10T23:59:59.000Z',
    status: 'pendente',
    createdAt: '2026-09-15T09:00:00.000Z',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-001',
    tenantId: 'traduztudo-matriz',
    description: 'Google Ads & Campanhas Tradução Juramentada SP',
    category: 'marketing',
    amount: 1450.0,
    date: '2026-09-15T12:00:00.000Z',
    paymentMethod: 'cartao_credito',
    createdAt: '2026-09-15T12:00:00.000Z',
  },
  {
    id: 'exp-002',
    tenantId: 'traduztudo-matriz',
    description: 'Assinatura Trados Studio & Ferramentas CAT',
    category: 'software',
    amount: 490.0,
    date: '2026-09-18T10:00:00.000Z',
    paymentMethod: 'cartao_credito',
    createdAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'exp-003',
    tenantId: 'traduztudo-matriz',
    description: 'Honorários Assessoria Contábil Mensal',
    category: 'contabilidade',
    amount: 750.0,
    date: '2026-09-20T08:00:00.000Z',
    paymentMethod: 'pix',
    createdAt: '2026-09-20T08:00:00.000Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-001',
    tenantId: 'traduztudo-matriz',
    title: 'Novo Lead Recebido',
    message: 'Camila Drummond solicitou orçamento para Apostilamento de Haia.',
    type: 'info',
    link: '/crm/leads',
    read: false,
    createdAt: '2026-09-30T01:15:00.000Z',
  },
  {
    id: 'notif-002',
    tenantId: 'traduztudo-matriz',
    title: 'Orçamento Aprovado!',
    message: 'Dr. Roberto Alencar aprovou o orçamento ORC-000001 (R$ 1.850,00).',
    type: 'success',
    link: '/operacao/orcamentos',
    read: true,
    createdAt: '2026-09-21T14:20:00.000Z',
  },
  {
    id: 'notif-003',
    tenantId: 'traduztudo-matriz',
    title: 'Prazo Próximo',
    message: 'A ordem de serviço OS-000003 (TechNova) tem prazo de entrega hoje às 19:00.',
    type: 'warning',
    link: '/operacao/ordens-servico/order-003',
    read: false,
    createdAt: '2026-09-30T03:00:00.000Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    tenantId: 'traduztudo-matriz',
    userId: 'user-juliana',
    userName: 'Juliana Mendes',
    action: 'Criação de Orçamento',
    entity: 'Quote',
    entityId: 'quote-001',
    details: 'Criou o orçamento ORC-000001 para o cliente Dr. Roberto Alencar no valor de R$ 1.850,00',
    createdAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'aud-002',
    tenantId: 'traduztudo-matriz',
    userId: 'user-mariana',
    userName: 'Mariana Costa',
    action: 'Aprovação de Orçamento',
    entity: 'Quote',
    entityId: 'quote-001',
    details: 'Orçamento aprovado pelo cliente via link digital com IP registrado 189.40.72.115',
    createdAt: '2026-09-21T14:20:00.000Z',
  },
  {
    id: 'aud-003',
    tenantId: 'traduztudo-matriz',
    userId: 'user-mariana',
    userName: 'Mariana Costa',
    action: 'Criação de Ordem de Serviço',
    entity: 'WorkOrder',
    entityId: 'order-001',
    details: 'Gerada automaticamente a partir da aprovação do orçamento ORC-000001',
    createdAt: '2026-09-21T14:30:00.000Z',
  },
  {
    id: 'aud-004',
    tenantId: 'traduztudo-matriz',
    userId: 'user-rodrigo',
    userName: 'Rodrigo Rocha',
    action: 'Registro de Pagamento',
    entity: 'AccountReceivable',
    entityId: 'rec-001',
    details: 'Confirmou recebimento da entrada via PIX de R$ 925,00 para a OS-000001',
    createdAt: '2026-09-21T15:10:00.000Z',
  },
];
